# token_embedder_type: "embedding"
model: "knrm"
knrm_kernels: 11

# sparse_gradient_embedding: True
# embedding_optimizer: sparse_adam
# use_fp16: False
#
# param_group0_learning_rate: 0.00001
# param_group1_names: ["kernel_bin_weights","kernel_alpha_scaler"]
# param_group1_learning_rate: 0.0001
